name: surgo_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  go_router: ^16.2.1
  google_fonts: ^6.3.1
  http: ^1.5.0
  provider: ^6.1.5+1
  email_validator: "^2.1.17"
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
